<a href="https://colab.research.google.com/github/linhoangce/tensorflow_learning_stuff/blob/main/tensorflow_tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import numpy as np

In [3]:
# Scalar
rank_0_tensor = tf.constant(5)
rank_0_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [6]:
# A vector - float tensor
rank_1_tensor = tf.constant([2.0, 3., 4.])
rank_1_tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([2., 3., 4.], dtype=float32)>

In [9]:
# Matrix
rank_2_tensor = tf.constant([[1,2],
                             [3,4],
                             [5,6]], dtype=tf.float16)
rank_2_tensor

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)>

In [32]:
# Tensor - multi-dimension array
rank_3_tensor = tf.constant([
    [[0, 1, 2, 4, 5],
     [6, 7, 8, 9, 10]],
    [[11, 12, 13, 14, 15],
     [16, 17, 18, 19, 20]],
    [[21, 22, 23, 24, 25],
     [26, 27, 28, 29, 30]]
])
rank_3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]], dtype=int32)>

In [11]:
# Convert tensor into numpy
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [12]:
rank_3_tensor.numpy()

array([[[ 0,  1,  2,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 0,  1,  2,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[ 0,  1,  2,  4,  5],
        [ 6,  7,  8,  9, 10]]], dtype=int32)

In [14]:
# Basic math operations
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]])

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b))

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32)


In [15]:
a + b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [16]:
a * b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [17]:
a @ b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 3],
       [7, 7]], dtype=int32)>

In [18]:
# tensors are used in all kinds of operations
c = tf.constant([[4., 5.],
                 [10., 1.]])

# find the largest value
tf.reduce_max(c)

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [19]:
# Find the index of the largest value
tf.math.argmax(c)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([1, 0])>

In [20]:
# Compute the softmax
tf.nn.softmax(c)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.6894143e-01, 7.3105854e-01],
       [9.9987662e-01, 1.2339458e-04]], dtype=float32)>

## About Shapes

Tensors have shapes:

* **Shape**: The length (number of elements) of each of the axes of a tensor
* **Rank**: Number of tensor axes. A scalar has rank 0, a vector has rank 1, a matrix rank 2
* **Axis** or **Dimension**: A particular dimension of a tensor
* **Size**: The total number of items in the tensor, the product of the shape vector's elements

** NOTE: Although there is a reference to "tensor of two dimensions", a rank-2 tensor does not usually describe a 2D space.

In [21]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(3, 2, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

Tensors and `tf.TensorShape` objects have convenient properties for accessing these:

In [23]:
print("Type of every element: ", rank_4_tensor.dtype)
print("Number of axes: ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along axis 0 of tensor: ", rank_4_tensor.shape[0])
print("elements along the last axis of tensor: ", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element:  <dtype: 'float32'>
Number of axes:  4
Shape of tensor:  (3, 2, 4, 5)
Elements along axis 0 of tensor:  3
elements along the last axis of tensor:  5
Total number of elements (3*2*4*5):  120


**NOTE**: the `Tensor.ndim` and `Tensor.shape` attributes don't return `Tensor` objects. If we need a `Tensor`, use `tf.rank` or `tf.shape` function. The difference is subtle, but it can be important when building graphs (later)

In [24]:
tf.rank(rank_4_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [25]:
tf.shape(rank_4_tensor)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 2, 4, 5], dtype=int32)>

## Manipulate Shapes

In [26]:
# Shape returns a `TensorShape` object that shows the size along each axis
x = tf.constant([[1], [2], [3]])
x.shape

TensorShape([3, 1])

In [27]:
# Convert to a Python list
x.shape.as_list()

[3, 1]

We can reshape a tensor into a new shape. The `tf.reshape` operation is fast and cheap as the underlying data does not need to be duplicated

In [30]:
# Note that we're passing in a list for reshaping
reshaped = tf.reshape(x, [1, 3])
print(x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


The data maintains its layout in memory and a new tensor is created, with the request shape, pointing to the same data. TensorFlow uses C-style "row-major" memory ordering, where incrementing the rightmost inde corresponds to a single step in memory.

In [33]:
rank_3_tensor

<tf.Tensor: shape=(3, 2, 5), dtype=int32, numpy=
array([[[ 0,  1,  2,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]], dtype=int32)>

In [34]:
# We can see what order is laid out in memory when flattening a tensor
# A `-1` passed in the `shape` argument says "Whatever fits"
tf.reshape(rank_3_tensor, [-1])

<tf.Tensor: shape=(30,), dtype=int32, numpy=
array([ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=int32)>

Typically, the only reasonable use of `tf.reshape` is to combine or split adjacent axes (or add/remove `1`s)


In [35]:
tf.reshape(rank_3_tensor, [3*2, 5])

<tf.Tensor: shape=(6, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]], dtype=int32)>

In [36]:
tf.reshape(rank_3_tensor, [3, -1])

<tf.Tensor: shape=(3, 10), dtype=int32, numpy=
array([[ 0,  1,  2,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]], dtype=int32)>

## Broadcasting

In [38]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])

print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


Likewise, axes with length 1 can be stretched out to match the other arguments. Both arguments can be stretched in the same computation.

In this case a 3x1 matrix is element-wise multiplied by a 1x4 matrix to produce a 3x4 matrix.

In [40]:
x = tf.reshape(x, [3, 1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


In [44]:
# What braodcasting looks like
tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3])

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]], dtype=int32)>